### ISSUE TITLE
Formularz kontaktowy

### ISSUE THREAD

**Issue by ispmor** [ispmor/space_reservation_system#11]
W sekcji kontakt należałoby dodać formularz kontaktowy umożliwiający wysłanie maila bezpośrednie do Administracji z strony głównej

**Comment by jbryl7** [comment]
zrobiłem to przy okazji jak robiłem register form i jest to na branchu register-form.
Merge requesta jeszcze nie wystawiam bo samych formularzy logowania/rejestrowania jeszcze nie skończyłem
